"""Build the final liquidation EDA notebook from generated full-data artifacts.

The expensive EDA pipeline writes compact CSV tables and PNG figures under
``reports/liquidation_eda``.  This script turns those artifacts into an
executed, readable notebook report without recomputing the 1B+ row pipeline.
"""

from __future__ import annotations

from pathlib import Path
import textwrap

import nbformat as nbf


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = ROOT / "notebooks" / "liquidation_eda.ipynb"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(textwrap.dedent(text).strip())


def code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(textwrap.dedent(source).strip())


def build_notebook() -> nbf.NotebookNode:
    cells = [
        md(
            """
            # Liquidation Market Data EDA

            **Goal.** Build intuition about Binance trades, Binance BBO,
            Binance liquidations, and Bybit liquidations through pure
            exploration before building any predictive signal.

            This notebook is an executable report over the full-data EDA
            artifacts generated by the project pipeline.  Core metrics and
            conclusions are computed on the full train/validation data; only
            distribution plots use deterministic visual samples to keep figures
            readable.

            **Author:** Sergei Smirnov
            **Project:** CMF HFT / market microstructure research
            """
        ),
        md(
            """
            ## 0. Reproducibility and Scope

            The raw parquet files are intentionally not committed.  The full EDA
            pipeline can be reproduced locally with:

            ```bash
            PYTHONPATH=src .venv/bin/python -m cmf_backtester.main run-liquidation-eda \\
              --config configs/liquidation_eda.yaml --profile full
            ```

            The latest full run processed more than one billion Binance trades,
            so this notebook does not rerun that expensive computation by
            default.  Instead it loads the generated full-data CSV tables and
            figures from `reports/liquidation_eda/`.
            """
        ),
        code(
            """
            from pathlib import Path
            import json
            import math

            import pandas as pd
            from IPython.display import Image, Markdown, display

            pd.set_option("display.max_columns", 40)
            pd.set_option("display.width", 160)
            pd.set_option("display.float_format", lambda x: f"{x:,.6g}")

            cwd = Path.cwd()
            ROOT = cwd if (cwd / "reports" / "liquidation_eda").exists() else cwd.parent
            REPORT_DIR = ROOT / "reports" / "liquidation_eda"
            TABLE_DIR = REPORT_DIR / "tables"
            FIG_DIR = REPORT_DIR / "figures"
            META_PATH = REPORT_DIR / "run_metadata.json"

            assert REPORT_DIR.exists(), f"Missing report directory: {REPORT_DIR}"
            assert META_PATH.exists(), f"Missing metadata: {META_PATH}"

            with META_PATH.open("r", encoding="utf-8") as f:
                metadata = json.load(f)

            def read_table(name: str) -> pd.DataFrame:
                path = TABLE_DIR / name
                assert path.exists(), f"Missing table: {path}"
                return pd.read_csv(path)

            def show_table(name: str, n: int = 12, sort_by=None, ascending=True, title: str | None = None) -> pd.DataFrame:
                df = read_table(name)
                view = df
                if sort_by is not None and sort_by in view.columns:
                    view = view.sort_values(sort_by, ascending=ascending)
                if title:
                    display(Markdown(f"**{title}**"))
                display(view.head(n))
                display(Markdown(f"`{name}`: {len(df):,} rows, {len(df.columns):,} columns."))
                return df

            def show_figure(name: str, width: int = 980) -> None:
                path = FIG_DIR / name
                assert path.exists(), f"Missing figure: {path}"
                display(Image(filename=str(path), width=width))

            display(Markdown(f"Loaded full EDA artifacts from `{REPORT_DIR}`."))
            """
        ),
        md(
            """
            The metadata below is the first sanity check: the notebook is reading
            a full-profile run, not a toy sample.  The row counts are also used
            later to verify that the full-data markout loop covered all Binance
            trades and all Binance BBO updates.
            """
        ),
        code(
            """
            meta_view = pd.DataFrame(
                [
                    ("profile", metadata.get("profile")),
                    ("generated_at_utc", metadata.get("generated_at_utc")),
                    ("full_data_mode", metadata.get("full_data_mode")),
                    ("processed_trade_rows_full", metadata.get("processed_trade_rows_full")),
                    ("processed_bbo_rows_full", metadata.get("processed_bbo_rows_full")),
                    ("processed_trade_batches_full", metadata.get("processed_trade_batches_full")),
                    ("full_data_dates_processed", metadata.get("full_data_dates_processed")),
                    ("full_data_batch_minutes", metadata.get("full_data_batch_minutes")),
                    ("full_data_eda_seconds", metadata.get("phase_seconds", {}).get("full_data_eda")),
                ],
                columns=["field", "value"],
            )
            display(meta_view)
            """
        ),
        md(
            """
            **Interpretation.** The EDA was run in full mode.  The key design
            choice was to process data symbol-by-symbol and day/hour batch by
            batch, writing compact aggregates instead of keeping enriched trades
            in memory.  This is the right style for HFT data: the full dataset is
            too large for notebook-first row-wise exploration.
            """
        ),
        md(
            """
            ## 1. Dataset Shape and Coverage

            First we inspect the four data families:

            - Binance trades;
            - Binance BBO / book ticker snapshots;
            - Binance liquidations;
            - Bybit liquidations.

            The purpose of this block is basic orientation: source sizes,
            date coverage, duplicate timestamps, and train/validation split
            balance.
            """
        ),
        code(
            """
            source_files = show_table("source_files.csv", n=8, title="Source files")
            time_coverage = show_table("time_coverage.csv", n=8, title="Time coverage and duplicate timestamps")
            train_validation_drift = show_table("train_validation_drift.csv", n=16, title="Train/validation row counts by source")
            """
        ),
        code(
            """
            expected_trades = (
                metadata["source_rows"]["binance_trades:btcusdt"]
                + metadata["source_rows"]["binance_trades:ethusdt"]
            )
            expected_bbo = (
                metadata["source_rows"]["binance_booktickers:btcusdt"]
                + metadata["source_rows"]["binance_booktickers:ethusdt"]
            )
            coverage_check = pd.DataFrame(
                [
                    ("Binance trades", expected_trades, metadata["processed_trade_rows_full"]),
                    ("Binance BBO", expected_bbo, metadata["processed_bbo_rows_full"]),
                ],
                columns=["family", "raw_rows_expected", "rows_processed_by_full_eda"],
            )
            coverage_check["match"] = coverage_check["raw_rows_expected"] == coverage_check["rows_processed_by_full_eda"]
            display(coverage_check)
            """
        ),
        md(
            """
            **Findings.**

            - The full EDA covers all Binance trades and all Binance BBO rows
              used for markouts and order-book diagnostics.
            - Trades have many duplicate timestamps.  This is expected in
              high-frequency market data: multiple executions can share the same
              microsecond timestamp.  The files do not provide a separate event
              sequence id, so same-timestamp ordering is ambiguous and must not
              be invented.
            - BBO rows have no duplicate timestamps in this dataset, which makes
              backward-as-of joins stable for book state lookup.
            - Bybit liquidation timestamps can duplicate; we treat them as event
              batches at the same visible time and apply the required 200 ms
              availability delay before using them as features.
            """
        ),
        code(
            """
            show_figure("event_counts_by_day.png")
            """
        ),
        md(
            """
            **Figure interpretation.** Event counts are plotted on a log scale
            because trades and BBO updates are orders of magnitude more frequent
            than liquidations.  This confirms the main practical constraint of
            the project: trades/BBO require batch aggregation, while
            liquidation data is sparse enough for richer event studies.
            """
        ),
        code(
            """
            daily_counts = read_table("daily_event_counts.csv")
            daily_intensity = (
                daily_counts
                .groupby(["source", "symbol"], as_index=False)
                .agg(
                    total_rows=("rows", "sum"),
                    median_rows_per_day=("rows", "median"),
                    p90_rows_per_day=("rows", lambda s: s.quantile(0.90)),
                    max_rows_per_day=("rows", "max"),
                    min_rows_per_day=("rows", "min"),
                )
            )
            daily_intensity["burst_ratio_max_to_median"] = (
                daily_intensity["max_rows_per_day"] / daily_intensity["median_rows_per_day"]
            )
            display(daily_intensity.sort_values(["source", "symbol"]))

            top_liquidation_days = (
                daily_counts[daily_counts["source"].str.contains("liquidations")]
                .sort_values("rows", ascending=False)
                .head(12)
            )
            display(Markdown("**Largest liquidation-count days**"))
            display(top_liquidation_days)
            """
        ),
        md(
            """
            **Quant research read.** The dataset is not a stationary stream of
            independent events.  Activity clusters by day and source.  For a
            trading signal this matters because a feature that works on quiet
            days may fail during liquidation cascades, and a model trained on raw
            event counts can overfit to volatility/activity regimes.  The right
            next step is therefore regime-aware validation: compare signal
            behavior on high-liquidation days, normal days, and weekend/low
            liquidity periods instead of trusting a single aggregate score.
            """
        ),
        md(
            """
            ## 2. Schema, Data Quality, and Conventions

            This block checks the conventions that can silently break a trading
            research task:

            - timestamps are UNIX microseconds in UTC;
            - Binance trade `side` is taker side;
            - liquidation `side` is liquidation order side;
            - Bybit liquidations become available only after 200 ms;
            - known-at-time joins must be backward/as-of joins.
            """
        ),
        code(
            """
            schema_audit = show_table("schema_audit.csv", n=8, title="Schema audit")
            bbo_quality = show_table("bbo_quality.csv", n=12, title="BBO quality by day")
            anomaly_log = show_table("anomaly_log.csv", n=25, title="Anomaly log")
            """
        ),
        md(
            """
            **Quality interpretation.**

            - Locked/crossed BBO rows are not present in the displayed daily
              quality sample, which is a good sign for top-of-book consistency.
            - The anomaly log is dominated by trade prices outside the previous
              BBO.  This is not automatically an error: trades and BBO updates
              are separate streams, and without exchange sequencing the previous
              BBO may lag the execution that changed the book.
            - Duplicate trade timestamps are real data properties, not row
              corruption.  Because no event id is available, the safest handling
              is deterministic sorting by timestamp plus conservative as-of
              joins, not artificial reconstruction of intra-timestamp order.
            """
        ),
        code(
            """
            trade_location = read_table("trade_price_location_summary.csv")
            location_summary = (
                trade_location.groupby(["split", "symbol", "side", "price_location"], as_index=False)["rows"].sum()
            )
            location_summary["share_within_side"] = (
                location_summary["rows"]
                / location_summary.groupby(["split", "symbol", "side"])["rows"].transform("sum")
            )
            display(location_summary.head(24))
            """
        ),
        code(
            """
            asof_sensitivity = show_table("asof_sensitivity.csv", n=16, title="Same-timestamp vs strictly previous BBO sensitivity")
            """
        ),
        md(
            """
            **Convention conclusion.** Buy trades are mostly at/above the ask and
            sell trades are mostly at/below the bid, supporting the stated
            convention that Binance trade side is taker side.  The same-timestamp
            sensitivity table keeps this honest: if allowing same-timestamp BBO
            materially changed the diagnostic, it would indicate sequencing
            risk.  The notebook therefore documents the ambiguity instead of
            pretending exact event order is recoverable.
            """
        ),
        code(
            """
            convention_view = location_summary.copy()
            convention_view["is_consistent_with_taker_side"] = (
                ((convention_view["side"] == "buy") & convention_view["price_location"].isin(["at_ask", "above_ask"]))
                | ((convention_view["side"] == "sell") & convention_view["price_location"].isin(["at_bid", "below_bid"]))
            )
            convention_score = (
                convention_view
                .groupby(["split", "symbol", "side", "is_consistent_with_taker_side"], as_index=False)["rows"]
                .sum()
            )
            convention_score["share"] = (
                convention_score["rows"]
                / convention_score.groupby(["split", "symbol", "side"])["rows"].transform("sum")
            )
            display(convention_score.sort_values(["split", "symbol", "side", "is_consistent_with_taker_side"]))
            """
        ),
        md(
            """
            **Trading implication.** The side convention is usable, but the
            trade-vs-BBO diagnostic also warns us that raw cross-stream alignment
            is not exchange-sequenced.  I would not use same-microsecond trade
            and BBO ordering as a hard label.  I would use robust windows,
            backward-as-of features, and explicit stale-book filters.  If a
            future alpha depends on knowing whether a trade happened before or
            after a same-timestamp book update, that alpha is not reliable with
            this data alone.
            """
        ),
        md(
            """
            ## 3. Distributions: Spread, Trade Size, Liquidation Size

            The next step is distributional intuition.  HFT data is heavy-tailed:
            most events are small, while a small number of large trades or
            liquidations dominate notional pressure.  That affects both plotting
            and feature design.
            """
        ),
        code(
            """
            show_figure("spread_distribution_bps.png")
            """
        ),
        md(
            """
            **Spread distribution.** Spreads are extremely tight in basis points,
            which is expected for liquid BTCUSDT/ETHUSDT perpetuals.  The plot is
            clipped in the far tail for readability; the clipped visualization is
            descriptive only, while quality and markout tables are full-data.
            """
        ),
        code(
            """
            show_figure("trade_notional_distribution.png")
            """
        ),
        md(
            """
            **Trade notional distribution.** Trade notionals are plotted on a
            log scale because the distribution is strongly right-tailed.  This is
            the reason the task uses clipped weights
            `min(price * amount, 100000)`: without clipping, a small number of
            very large prints could dominate weighted maker-PnL estimates.
            """
        ),
        code(
            """
            show_figure("liquidation_notional_distribution.png")
            """
        ),
        md(
            """
            **Liquidation notional distribution.** Liquidations are much sparser
            than trades but also heavy-tailed.  This motivates bucketed analyses:
            small liquidation events and liquidation clusters should not be
            treated as equivalent.
            """
        ),
        code(
            """
            trade_summary = show_table("trade_summary.csv", n=16, title="Trade summary")
            liquidation_summary = show_table("liquidation_summary.csv", n=16, title="Liquidation summary")
            """
        ),
        code(
            """
            liq_daily = (
                daily_counts[daily_counts["source"].str.contains("liquidations")]
                .groupby(["date", "symbol"], as_index=False)["rows"].sum()
                .rename(columns={"rows": "liquidation_rows"})
            )
            trade_daily = (
                daily_counts[daily_counts["source"].eq("binance_trades")]
                .groupby(["date", "symbol"], as_index=False)["rows"].sum()
                .rename(columns={"rows": "trade_rows"})
            )
            daily_activity = trade_daily.merge(liq_daily, on=["date", "symbol"], how="left").fillna({"liquidation_rows": 0})
            daily_activity["liquidations_per_million_trades"] = (
                daily_activity["liquidation_rows"] / daily_activity["trade_rows"] * 1_000_000
            )
            display(daily_activity.sort_values("liquidations_per_million_trades", ascending=False).head(12))
            """
        ),
        md(
            """
            **Alpha-search read.** Liquidations should not be treated only as
            another volume field.  The interesting object is forced flow relative
            to normal trade activity: high liquidation-per-trade days are
            candidates for stress regimes where passive fills are more toxic and
            continuation/reversal patterns can differ from ordinary flow.  This
            motivates features such as recent liquidation pressure divided by
            recent trade notional or BBO update rate, not just raw liquidation
            notional.
            """
        ),
        md(
            """
            ## 4. Order Book State: Queue Imbalance and OFI

            This block asks whether the book contains short-horizon directional
            information.  Two classical microstructure quantities are used:

            - queue imbalance: bid size / (bid size + ask size);
            - order-flow imbalance (OFI): signed change in top-of-book pressure.

            These are not trading signals yet; they are diagnostics for whether
            the market state is informative.
            """
        ),
        code(
            """
            qi = read_table("queue_imbalance_next_move.csv")
            qi_pivot = qi.pivot_table(
                index=["split", "symbol"],
                values=["prob_next_move_up", "no_mid_move_share"],
                aggfunc=["min", "max", "mean"],
            )
            display(qi.head(20))
            display(qi_pivot)
            """
        ),
        code(
            """
            show_figure("queue_imbalance_next_move_probability.png")
            """
        ),
        md(
            """
            **Queue imbalance finding.** Conditional on a mid-price move
            occurring at the next BBO event, the probability of an upward move is
            monotonic in queue imbalance.  Low bid-side queue share predicts
            downward moves; high bid-side queue share predicts upward moves.
            Most consecutive BBO events do not move the mid-price, so the plot
            distinguishes `P(next mid up | mid moved)` from raw next-event
            probabilities.
            """
        ),
        code(
            """
            ofi = show_table("bbo_ofi_summary.csv", n=8, title="OFI summary")
            """
        ),
        code(
            """
            show_figure("ofi_vs_future_return.png")
            """
        ),
        md(
            """
            **OFI finding.** OFI has a positive same-direction relationship with
            next BBO returns in both symbols and both splits.  This is consistent
            with Cont-Kukanov-Stoikov style intuition: changes in displayed
            queue pressure are informative about short-horizon price formation.
            """
        ),
        md(
            """
            ## 5. Baseline Maker Markout

            The task's maker-PnL markout is:

            $$
            \\operatorname{pnl}_i(\\tau) =
            -s_i \\frac{m_i(\\tau)-p_i}{p_i} \\cdot 10000
            + \\operatorname{maker\\_rebate\\_bps}
            $$

            where `s_i = +1` for taker buy / maker sell and `s_i = -1` for
            taker sell / maker buy.  This is a diagnostic for adverse selection:
            after a trade, did the future mid move against the passive maker?
            """
        ),
        code(
            """
            markout = read_table("full_markout_summary.csv")
            display(markout)
            best = markout.sort_values("weighted_pnl_bps", ascending=False).head(8)
            worst = markout.sort_values("weighted_pnl_bps", ascending=True).head(8)
            display(Markdown("**Best full-data markout buckets**"))
            display(best)
            display(Markdown("**Worst full-data markout buckets**"))
            display(worst)
            """
        ),
        code(
            """
            show_figure("markout_curve_by_side_symbol.png")
            """
        ),
        md(
            """
            **Markout curve interpretation.** Markouts are small in absolute bps
            terms but economically meaningful at HFT scale.  The curves differ
            by symbol, side, horizon, and split.  This means a future filter
            should not assume a single universal effect: side, horizon and asset
            matter.
            """
        ),
        code(
            """
            stability = (
                markout.pivot_table(
                    index=["symbol", "side", "horizon_seconds"],
                    columns="split",
                    values="weighted_pnl_bps",
                    aggfunc="first",
                )
                .reset_index()
            )
            if {"train", "validation"}.issubset(stability.columns):
                stability["validation_minus_train_bps"] = stability["validation"] - stability["train"]
                stability["same_sign"] = (stability["train"] * stability["validation"]) > 0
            display(stability.sort_values("horizon_seconds").head(28))
            """
        ),
        md(
            """
            **Researcher interpretation.** The raw maker markout is a baseline
            toxicity map, not the final signal.  A positive bucket means a
            passive maker would have benefited after those trades; a negative
            bucket means adverse selection.  The important question is not
            whether the average markout is positive everywhere, but where it is
            predictably different from baseline and stable from train to
            validation.  Buckets that flip sign between train and validation are
            weak alpha candidates unless they can be explained by a regime
            variable.
            """
        ),
        code(
            """
            show_figure("markout_distribution_by_tau.png")
            """
        ),
        md(
            """
            **Distribution interpretation.** The distribution plot highlights
            tail risk around markouts.  Mean/weighted mean alone is not enough:
            a strategy can look acceptable on average while being exposed to
            occasional adverse-selection bursts.
            """
        ),
        code(
            """
            daily_markout = read_table("full_daily_weighted_markout.csv")
            daily_focus = daily_markout.query("horizon_seconds in [30, 120, 300]").head(20)
            display(daily_focus)
            display(Markdown(f"`full_daily_weighted_markout.csv`: {len(daily_markout):,} rows."))
            """
        ),
        md(
            """
            ## 6. Liquidation Context

            Now we test the key exploratory idea: liquidations may reveal forced
            directional pressure.  Liquidation `side` is interpreted as
            liquidation order side:

            - `buy`: forced buy / short liquidation / upward pressure;
            - `sell`: forced sell / long liquidation / downward pressure.

            Binance liquidation context uses its event timestamp.  Bybit context
            uses `available_timestamp = timestamp + 200_000`, because this is the
            first time the event could be known in a Binance trading system.
            """
        ),
        code(
            """
            context = read_table("full_markout_by_liquidation_context.csv")
            focus_context = context[
                (context["horizon_seconds"].isin([30, 120, 300]))
                & (context["window_seconds"].isin([1, 5, 30, 120]))
            ].head(30)
            display(focus_context)
            """
        ),
        md(
            """
            **Liquidation context interpretation.** The table compares maker
            markout conditional on recent upward/downward/no liquidation
            pressure.  This is closer to a usable feature than raw event counts:
            it asks whether the maker's future markout changes after a known
            liquidation pressure regime.
            """
        ),
        code(
            """
            baseline_context = (
                context[context["liq_pressure_bucket"].eq("no_pressure")]
                [["split", "symbol", "side", "venue", "window_seconds", "horizon_seconds", "weighted_pnl_bps"]]
                .rename(columns={"weighted_pnl_bps": "baseline_no_pressure_pnl_bps"})
            )
            context_edge = context.merge(
                baseline_context,
                on=["split", "symbol", "side", "venue", "window_seconds", "horizon_seconds"],
                how="left",
            )
            context_edge["edge_vs_no_pressure_bps"] = (
                context_edge["weighted_pnl_bps"] - context_edge["baseline_no_pressure_pnl_bps"]
            )
            robust_validation_edges = context_edge[
                (context_edge["split"].eq("validation"))
                & (~context_edge["liq_pressure_bucket"].eq("no_pressure"))
                & (context_edge["rows"] >= 1_000_000)
                & (context_edge["horizon_seconds"].isin([30, 120, 300]))
            ]
            display(Markdown("**Largest positive validation edges vs no-pressure baseline**"))
            display(robust_validation_edges.sort_values("edge_vs_no_pressure_bps", ascending=False).head(12))
            display(Markdown("**Largest negative validation edges vs no-pressure baseline**"))
            display(robust_validation_edges.sort_values("edge_vs_no_pressure_bps", ascending=True).head(12))
            """
        ),
        md(
            """
            **Signal-design read.** This is where the EDA becomes actionable.
            The useful object is the incremental edge versus a no-liquidation
            baseline under the same symbol, side, venue, window and horizon.
            Large positive edges suggest situations where the passive maker's
            adverse selection is reduced or reversed; large negative edges
            suggest toxic flow where a filter should avoid providing liquidity.
            I would not trade the top rows directly; I would first require
            train/validation stability, turnover capacity, and robustness across
            neighboring windows.
            """
        ),
        code(
            """
            nonlinear = read_table("nonlinear_flow_response.csv")
            display(nonlinear.head(24))
            """
        ),
        code(
            """
            show_figure("nonlinear_flow_response.png")
            """
        ),
        md(
            """
            **Nonlinear response interpretation.** Bucketed pressure diagnostics
            are important because liquidation effects are unlikely to be linear.
            The zero-pressure bucket acts as a baseline; positive and negative
            buckets show whether increasing liquidation pressure changes the
            expected maker markout.
            """
        ),
        code(
            """
            signed_response = read_table("signed_flow_response_functions.csv")
            display(signed_response.head(28))
            """
        ),
        code(
            """
            show_figure("signed_flow_response_functions.png")
            """
        ),
        md(
            """
            **Signed response interpretation.** Signed-flow response functions
            measure how future mid returns respond to signed trade or
            liquidation pressure.  This is the bridge between simple EDA and
            market-impact intuition: if signed forced flow has a persistent
            response, it can motivate future filtering features.
            """
        ),
        md(
            """
            ## 7. True Liquidation Event Study

            A true event study aligns the Binance mid-price around liquidation
            event time and then averages the return path.  For Bybit the event
            time is the delayed availability timestamp, not the raw exchange
            timestamp.  This avoids look-ahead in cross-exchange analysis.
            """
        ),
        code(
            """
            event_study = read_table("event_study_summary.csv")
            display(event_study.head(20))
            display(Markdown(f"`event_study_summary.csv`: {len(event_study):,} rows."))
            """
        ),
        code(
            """
            show_figure("liquidation_event_study_mid.png")
            """
        ),
        md(
            """
            **Aggregated event-study interpretation.** This figure aggregates
            liquidation event paths by venue and side.  The objective is not to
            prove causality but to detect whether the book moves systematically
            before or after visible liquidation pressure.
            """
        ),
        code(
            """
            show_figure("liquidation_event_study_by_venue_side_symbol.png")
            """
        ),
        md(
            """
            **Detailed event-study interpretation.** The detailed plot separates
            symbol, venue and side.  This is useful for identifying effects that
            exist in BTC but not ETH, or on Binance liquidations but not Bybit
            liquidations after the 200 ms information delay.
            """
        ),
        code(
            """
            event_wide = (
                event_study[event_study["offset_seconds"].isin([-300, -60, 0, 60, 300])]
                .pivot_table(
                    index=["split", "symbol", "venue", "side"],
                    columns="offset_seconds",
                    values="mean_return_bps",
                    aggfunc="mean",
                )
                .reset_index()
            )
            for col in [-300, -60, 0, 60, 300]:
                if col not in event_wide.columns:
                    event_wide[col] = math.nan
            event_wide["post_300_minus_event_bps"] = event_wide[300] - event_wide[0]
            event_wide["event_minus_pre_300_bps"] = event_wide[0] - event_wide[-300]
            display(event_wide.sort_values("post_300_minus_event_bps", ascending=False).head(16))
            """
        ),
        md(
            """
            **Event-study read.** The pre-event leg is as important as the
            post-event leg.  If most of the move happens before the liquidation
            print is available, the liquidation is mainly a stress marker, not a
            tradable leading signal.  If a post-event drift remains after the
            Bybit 200 ms delay, that is more promising for a cross-exchange
            feature.  The next research step is to separate continuation from
            reversal after large liquidation clusters and condition on spread,
            OFI and queue imbalance at the time of availability.
            """
        ),
        md(
            """
            ## 8. Hypotheses Checked

            The exploration supports several concrete hypotheses for a future
            signal-design phase:

            1. **Queue imbalance is directionally informative.** Conditional
               next-mid-up probability is monotonic in queue imbalance buckets.
            2. **OFI carries short-horizon price-formation information.** OFI is
               positively related to next BBO returns in both symbols and both
               splits.
            3. **Liquidation context changes maker markout.** Recent signed
               liquidation pressure can shift the distribution of future maker
               markout relative to no-pressure periods.
            4. **Effects are conditional, not universal.** Symbol, side, horizon,
               venue and train/validation split all matter.
            5. **Timestamp conventions materially matter.** Duplicate trade
               timestamps and cross-source timing mean that backward/as-of
               semantics and Bybit's 200 ms delay must be explicit in any
               future model.

            **Practical trading hypothesis.** The most plausible strategy is not
            "trade every liquidation".  A more defensible approach is a passive
            maker filter: avoid quotes when recent forced flow, OFI and queue
            imbalance jointly imply toxic continuation; become more willing to
            provide liquidity when forced flow appears exhausted and markout
            improves versus the no-pressure baseline.
            """
        ),
        code(
            """
            hypotheses_path = ROOT / "docs" / "research" / "notes" / "liquidation_signal_hypotheses.md"
            if hypotheses_path.exists():
                text = hypotheses_path.read_text(encoding="utf-8")
                display(Markdown(text[:5000] + ("\\n\\n..." if len(text) > 5000 else "")))
            else:
                display(Markdown("Hypotheses note was not found."))
            """
        ),
        md(
            """
            ## 9. Limitations and Next Steps

            **Limitations.**

            - Same-timestamp event ordering is not recoverable from these files
              because no sequence id is provided.
            - Distribution plots use deterministic visual samples; conclusions
              are based on full-data aggregate tables.
            - The EDA is descriptive.  It does not yet define a final binary
              filter, train a model, or estimate live execution PnL.
            - Markouts are labels/diagnostics, not executable profits by
              themselves.

            **Next steps.**

            - Build candidate features from queue imbalance, OFI, recent
              liquidation pressure, cross-venue pressure and volatility regime.
            - Use chronological train/validation only; keep any final test or
              hidden set untouched.
            - Evaluate a simple interpretable binary filter before considering
              more complex ML.
            - Validate stability by symbol, side, day and market regime.
            """
        ),
        code(
            """
            final_checks = pd.DataFrame(
                [
                    ("full-data Binance trade coverage", bool(coverage_check.loc[coverage_check["family"] == "Binance trades", "match"].iloc[0])),
                    ("full-data Binance BBO coverage", bool(coverage_check.loc[coverage_check["family"] == "Binance BBO", "match"].iloc[0])),
                    ("required report exists", (REPORT_DIR / "liquidation_eda_report.md").exists()),
                    ("figures directory exists", FIG_DIR.exists()),
                    ("tables directory exists", TABLE_DIR.exists()),
                    ("Bybit delay documented", True),
                    ("no raw parquet embedded in notebook", True),
                ],
                columns=["check", "passed"],
            )
            display(final_checks)
            assert final_checks["passed"].all()
            """
        ),
        md(
            """
            ## Appendix: Optional Full Pipeline Command

            The cell below is intentionally non-running by default.  Turn
            `RUN_FULL_PIPELINE` to `True` only when you want to regenerate all
            full-data artifacts from raw parquet files.  The latest full run took
            roughly 98 minutes on the local machine.
            """
        ),
        code(
            """
            RUN_FULL_PIPELINE = False

            if RUN_FULL_PIPELINE:
                import subprocess
                cmd = [
                    str(ROOT / ".venv" / "bin" / "python"),
                    "-m",
                    "cmf_backtester.main",
                    "run-liquidation-eda",
                    "--config",
                    "configs/liquidation_eda.yaml",
                    "--profile",
                    "full",
                ]
                subprocess.run(cmd, cwd=ROOT, check=True, env={**__import__("os").environ, "PYTHONPATH": "src"})
            else:
                display(Markdown("Full pipeline execution skipped. Existing full-data artifacts were loaded above."))
            """
        ),
    ]

    notebook = nbf.v4.new_notebook(cells=cells)
    notebook["metadata"] = {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "pygments_lexer": "ipython3",
        },
    }
    return notebook


def main() -> None:
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    notebook = build_notebook()
    nbf.write(notebook, NOTEBOOK_PATH)
    print(f"Wrote {NOTEBOOK_PATH}")


if __name__ == "__main__":
    main()
